services:
  ejbca:
    hostname: ejbca
    container_name: ejbca
    image: "keyfactor/ejbca-ce:8.3.2"
    environment:
      - DATABASE_JDBC_URL=jdbc:postgresql://chainloop-lab-postgresql-1:5432/ejbca
      - DATABASE_USER=ejbca
      - DATABASE_PASSWORD=ejbca
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=later
      - PROXY_HTTP_BIND=0.0.0.0
  signserver:
    hostname: signserver
    container_name: signserver
    image: "keyfactor/signserver-ce:6.2.0"
    environment:
      - DATABASE_JDBC_URL=jdbc:postgresql://chainloop-lab-postgresql-1:5432/signserver
      - DATABASE_PASSWORD=signserver
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=later
      - PROXY_HTTP_BIND=0.0.0.0
  nginx:
    hostname: registry.community2024.local
    container_name: nginx
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # main configuration
      - ./container-configs/nginx/conf:/etc/nginx
      # TLS keys
      - ./container-configs/nginx/tls:/etc/nginx/tls
  registry:
    hostname: zot-registry
    container_name: zot-registry 
    image: "ghcr.io/project-zot/zot-linux-amd64:latest"
    volumes:
      # containers
      - ./container-configs/containers:/var/lib/registry
      - ./container-configs/zot/conf/zot-config.json:/etc/zot/config.json:ro
    #networks:
      #chainloop-lab_default:
        #aliases:
          #- registry.community2024.local

