# Copyright 2024 The Chainloop Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: workflowcontract.chainloop.dev/v1
kind: Policy
metadata:
  name: cyclonedx-banned-licenses
  description: Checks CycloneDX 1.5+ report for components banned licenses. It accepts a comma-separated list of licenses the argument "licenses"
  annotations:
    category: sbom
spec:
  type: SBOM_CYCLONEDX_JSON
  embedded: |
    package banned_licenses

    import rego.v1

    # ensure argument is always an array
    banned_licenses contains license if {
      is_array(input.args.licenses)
      some license in input.args.licenses
    }

    banned_licenses contains license if {
      not is_array(input.args.licenses)
      license := input.args.licenses
    }

    violations contains ref if {
      some i
      comp := input.components[i]
      some j
      license := comp.licenses[j].license
      banned(license, banned_licenses[k])
      ref := sprintf("Forbidden license %v for %v (%v)", [banned_licenses[k], comp.name, comp["bom-ref"]])
    }

    # Both id and name fields can be used to reference licenses
    banned(license, id) if {
      license.name == id
    }

    banned(license, id) if {
      license.id == id
    }
